# This is a basic workflow to publish the ISO to the releases section

on:
  push:
    branches: [ master ]
    tags:
      - v* # Push events to matching v*, i.e. v1.0, v20.15.10
  pull_request:
    branches: [ master ]
    tags:
      - v* # Push events to matching v*, i.e. v1.0, v20.15.10

name: release ISO

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Check if Git tag exists
        #run: echo "::set-env name=HEAD_TAG::$(git tag --points-at HEAD)"
        run:  echo "TAG_HEAD=$(git tag --points-at HEAD)" >> $GITHUB_ENV
      - name: Runs only if Git tag exists
        run: echo "This runs because Git tag points at HEAD ..."
        if: env.TAG_HEAD != ''        
      - name: Build project # This would actually build your project, using zip for an example artifact
        if: env.TAG_HEAD != '' 
        run: |
          wget -O - https://raw.githubusercontent.com/tracelabs/tlosint-live/dev/build_tracelabsiso_recipe.sh | sudo bash
          zip -s 1500m kali-linux-rolling-live-tracelabs-amd64.zip /opt/live-build-config/images/kali-linux-rolling-live-tracelabs-amd64.iso
          ls -lah kali-linux-rolling-live-tracelabs-amd64.zip
      - name: create-checksum-ISO
        if: env.TAG_HEAD != '' 
        run: sha256sum /opt/live-build-config/images/kali-linux-rolling-live-tracelabs-amd64.iso > checksums.txt
      - name: create-checksum-zip1
        if: env.TAG_HEAD != '' 
        run: sha256sum kali-linux-rolling-live-tracelabs-amd64.zip >> checksums.txt
      - name: create-checksum-zip2
        if: env.TAG_HEAD != '' 
        run: sha256sum kali-linux-rolling-live-tracelabs-amd64.z01 >> checksums.txt             
      - name: Create Release
        if: env.TAG_HEAD != '' 
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG_HEAD }}
          release_name: Release ${{ env.TAG_HEAD }}
          draft: false
          prerelease: false
      - name: Upload Release Asset part I
        if: env.TAG_HEAD != '' 
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./kali-linux-rolling-live-tracelabs-amd64.z01
          asset_name: TLosint-live-${{ env.TAG_HEAD }}.z01
          asset_content_type: application/zip
      - name: Upload Release Asset part II
        if: env.TAG_HEAD != '' 
        id: upload-release-asset2 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./kali-linux-rolling-live-tracelabs-amd64.zip
          asset_name: TLosint-live-${{ env.TAG_HEAD }}.zip
          asset_content_type: application/zip
      - name: upload-SHA256checksums
        if: env.TAG_HEAD != '' 
        id: upload-release-asset-checksums 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./checksums.txt
          asset_name: sha256-checksums_${{ env.TAG_HEAD }}.txt
          asset_content_type: text/plain

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
